#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: ursa-wrapper-go
  description: Hyperledger Ursa is a shared cryptography library
  homepage: https://wiki.hyperledger.org/display/ursa
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
